### ISSUE TITLE
Use helper module

### ISSUE THREAD

**Issue by steelbrain** [mybuddymichael/linter-elm-make#1]
We have an npm module `atom-linter` that provides a nicer API around BufferedProcess. You might wanna use it.

**Comment by mybuddymichael** [comment]
Right on. Did I miss that in the [linter docs](https://github.com/atom-community/linter/wiki) somewhere?

**Comment by steelbrain** [comment]
It was updated just recently. I won't blame you.

**Comment by mybuddymichael** [comment]
Hah. Thanks?

**Comment by steelbrain** [comment]
Look at the `init.coffee` here https://github.com/atom-community/linter/wiki/Migrating-to-the-new-API

**Comment by mybuddymichael** [comment]
Ah, okay. I don't think I ever looked closely at migrating to the new API since I was never using the old one. Thanks.
