### ISSUE TITLE
Is there a way to turn off the tool tip?

### ISSUE THREAD

**Issue by iamwilhelm** [mybuddymichael/linter-elm-make#102]
I couldn't find it in the readme, but is there a way to turn off the tooltip? A lot of the times, it obstructs the code I have to edit, especially if the error is large. I'm pretty good with just the error that shows up at the bottom bar.

**Comment by halohalospecial** [comment]
The option you're looking for is `Show Inline Error Tooltips` of the Linter package.  There's also relevant discussion here: https://github.com/mybuddymichael/linter-elm-make/issues/75
