### ISSUE TITLE
Feature: Show inferred type annotations

### ISSUE THREAD

**Issue by halohalospecial** [mybuddymichael/linter-elm-make#116]
Should we add this? @mybuddymichael @splodingsocks

With `Lint On The Fly` disabled:
![show-inferred-type-annotations](https://raw.githubusercontent.com/halohalospecial/linter-elm-make/show-inferred-type-annotations/images/show-inferred-type-annotations.gif)

With `Lint On The Fly` enabled:
![show-inferred-type-annotations-2](https://raw.githubusercontent.com/halohalospecial/linter-elm-make/show-inferred-type-annotations/images/show-inferred-type-annotations-2.gif)

**Comment by opsb** [comment]
My annotations tend to come later, this would fit into my workflow very nicely

**Comment by halohalospecial** [comment]
PR here: https://github.com/mybuddymichael/linter-elm-make/pull/117

**Comment by mybuddymichael** [comment]
I'm down.

**Comment by halohalospecial** [comment]
Hi @mybuddymichael, care to elaborate? :-) It's disabled by default.  It looks useful for cases like what @opsb mentioned and for beginners, but I'm not yet sure how useful it would be in practice.  Do you have a specific argument against it?

**Comment by mybuddymichael** [comment]
Hah, sorry, I meant that I think it looks cool! Nice work!

**Comment by halohalospecial** [comment]
Hah!  Tbh, this is the first time I encountered that expression, sorry :blush: I'm not too attached to the feature, so I'm fine either way :grin: Though it looks like others like it.  I'll prepare a new release.  Thanks!
