### ISSUE TITLE
Change default linter style for Elm?

### ISSUE THREAD

**Issue by halohalospecial** [mybuddymichael/linter-elm-make#119]
Hi!

With message styling and diffs added in the latest version, its difficult to make both the inline tooltip and linter panel readable at the same time because they have different background colors.

Linter default:
![linter-default](https://cloud.githubusercontent.com/assets/2138906/22410259/ddef4836-e6d0-11e6-8276-f1722e2578d6.png)

One solution is make them look the same:
![linter-proposed](https://cloud.githubusercontent.com/assets/2138906/22410262/ef89f690-e6d0-11e6-808e-5e8229dd3ef8.png)
This will only affect inline tooltips for Elm editors.  Tooltips for other languages will still use the linter default.

An alternative is to let the user change the styles of the diffs to suit their theme.  It might be cumbersome though.

Any other suggestions?

@mybuddymichael @splodingsocks

**Comment by mybuddymichael** [comment]
Will this create the opposite problem for those who use a light theme?

**Comment by halohalospecial** [comment]
@mybuddymichael, the inline tooltip will just follow the style of the bottom panel, so there should be no problem.  `.less` variables such as `@text-color-success` and `@text-color-error` are used to get the colors from the active UI theme.

**Comment by mybuddymichael** [comment]
Awesome. Sounds good then. And I'd veer away from any configuration.

**Comment by halohalospecial** [comment]
Version 0.21.0 released!
