### ISSUE TITLE
Problem with the "repository" field.

### ISSUE THREAD

**Issue by alehostert** [mybuddymichael/linter-elm-make#126]
Hello.

I'm having this error on my atom:

```
Error in $: Problem with the "repository" field.

The given domain does not start with <https://github.com/>
at line 1 col 1 in Main.elm
```

My repository is hosted on gitlab, not github, but this should not be an issue :)

**elm-package.json (part of it)**
```
    "version": "0.1.0",
    "summary": "description",
    "repository": "https://gitlab.com/myuser/myproject.git",
```

**Comment by halohalospecial** [comment]
Hi @Hostert, this is a known `elm-make` issue.  There's relevant discussion at https://github.com/elm-lang/elm-make/issues/71
