### ISSUE TITLE
Uncaught Error: EACCES: permission denied, mkdir '/src'

### ISSUE THREAD

**Issue by safhac** [mybuddymichael/linter-elm-make#137]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [linter-elm-make](https://github.com/mybuddymichael/linter-elm-make) package 0.23.1

### Stack Trace

Uncaught Error: EACCES: permission denied, mkdir '/src'

```
At /home/safhac/.atom/packages/linter-elm-make/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:47

Error: EACCES: permission denied, mkdir '/src'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at mkdirsSync (/packages/linter-elm-make/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:29:9)
    at Object.mkdirsSync (/packages/linter-elm-make/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:35:16)
    at Object.copySync (/packages/linter-elm-make/node_modules/fs-extra/lib/copy-sync/copy-sync.js:31:36)
    at /packages/linter-elm-make/lib/linter-elm-make.js:516:12
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 1.3.0 
elm 0.1.0 
elm-format 2.1.0 
elm-snippets 0.1.0 
elmjutsu 5.3.3 
html-to-elm 0.2.0 
intentions 1.1.2 
language-elm 1.5.0 
linter 2.1.0 
linter-elm-make 0.23.1 
linter-ui-default 1.1.0 
```
for some reason it fails to execute mkdir?
if it's chmod then please tell me which dir since i get the same error after 777

**Comment by halohalospecial** [comment]
Hi @safhac!  Looks like you set a value for `Work Directory`.  If so, make sure that the directory exists and has proper permissions.  I'm guessing you put "/src" in the textbox.

You don't usually need to set the value of `Work Directory` (it's mostly used for skipping the step of copying files when linting on the fly).  If that option is left blank and you have `Lint On The Fly` enabled, the package will use a temporary directory.  Try leaving it blank first.

**Comment by safhac** [comment]
yup that fixed it
