### ISSUE TITLE
elm-make process starts many many times

### ISSUE THREAD

**Issue by anagrius** [mybuddymichael/linter-elm-make#150]
Hi, I work at Humio where we have an Elm project of 50k+ lines of Elm code.
First off, we love atom-elm-make. But the latest few releases have made Atom almost unusable because of atom-elm-make. Atom becomes sluggish and unresponsive.

<img width="650" alt="screen shot 2017-08-31 at 12 33 42" src="https://user-images.githubusercontent.com/157210/29919283-01ae7844-8e49-11e7-9a0d-7d7aa78d98a0.png">

As the picture shows, we seem to get a lot of elm-make processes spun up as we edit the project. We tend to save quite often, but lately we have started seeing an very large performance hit.

Also more often than not `elm-make` times out. See picture

<img width="509" alt="screen shot 2017-08-31 at 12 38 04" src="https://user-images.githubusercontent.com/157210/29919387-61156162-8e49-11e7-908b-b23c4495dc5e.png">

I would love to be of help. (Helping myself) :)

**Comment by halohalospecial** [comment]
@anagrius, there is a queue so it should not spin up lots of elm-make processes :sweat_smile: I have to check it out.  Do you think it's safe to just kill the running elm-make process when the user saves again?

**Comment by anagrius** [comment]
Yes, I have been doing it for some plugins I have made. The elm-compiler handles SIGTERM well (from my experience)

**Comment by halohalospecial** [comment]
Hi @anagrius, can you try the latest version (v0.24.1)?  Thanks!

**Comment by anagrius** [comment]
I have and 0.24.2 as well. Same result:

<img width="732" alt="screen shot 2017-09-01 at 21 26 30" src="https://user-images.githubusercontent.com/157210/29984850-9c402b46-8f5c-11e7-8231-726d23924d6e.png">

Steps to reproduce:

1. Change elm file
2. Hit Cmd-S within a second
3. GOTO 1.

That will quickly spin up a bunch of processes (I checked that I don't have webpack or something else that would spin them up).

The processes keep running for a LONG time. As in hours. We can reproduce this on several machines.

Here is a process Dump of one of the `elm-make` processes (don't know if that will help).

[process.txt](https://github.com/mybuddymichael/linter-elm-make/files/1271329/process.txt)

**Comment by halohalospecial** [comment]
Hi @anagrius,

Have you also tried it on Linux?
How long does it take when running `elm-make` in the command line?
Have you tried using other editors/IDEs? (Just want to factor out if it's linter-elm-make-specific.)
I can test it out if you can point me to a sample repository.
Thanks!

**Comment by anagrius** [comment]
I have not tried on linux no. A full non-incremental build of the app including dependencies from CLI is approx.18 seconds.
It is definitely `linter-elm-make` spinning up elm-make, if I disable it I have no problems.
I can't really point you to a sample repo since it is a proprietary product :( But I don't see how the code could make this happen.

**Comment by halohalospecial** [comment]
Hi @anagrius,

I was able to confirm that it takes longer for the `elm-make` processes to complete when saving multiple times.  We're using `atom-linter`'s `exec` function with [unique spawning](https://www.npmjs.com/package/atom-linter#unique-spawning) at the moment.  I'll check if it's related to that.  Thanks for the inputs!

**Comment by anagrius** [comment]
Disabling Always Compile Main is a workaround for us since it reduces the compile time. But, of course we don't catch errors as quickly. Maybe it would be an idea to implement a command for:

linter-elm-make:compile-main

Just so you could easily trigger a compile of the entire project (when you want to) instead of having to jump to Main.elm and compile it or toggle "Always compile main" on and off.

Of course that has nothing to do directly with "Linter" :) But would be a great addition.

**Comment by halohalospecial** [comment]
@mybuddymichael, @splodingsocks, what do you think of this feature?  I'm okay with it.

**Comment by mrmurphy** [comment]
That sounds fine to me 👍 .

**Comment by halohalospecial** [comment]
Hi @anagrius, I think the issue is related to https://github.com/elm-lang/elm-compiler/issues/1473.  It seems that there are issues when multiple `elm-make` processes are running at the same time.

You can try the following (I only tested this on Lubuntu 17.04):
1. Install `libsysconfcpus`
```
git clone https://github.com/obmarg/libsysconfcpus.git
cd libsysconfcpus
./configure
make
sudo make install
```
2. Put the following in a file (e.g. `elm-make-2`):
```
sysconfcpus -n 1 elm-make $1 $2 $3
```

3. In the Settings view, set the elm-make executable path of `linter-elm-make` to the path of the file in Step 2.

The results are promising :smile: Saving multiple times will not affect the completion time of the latest `elm-make` process.
