### ISSUE TITLE
“The linter (or nuclide) package was not loaded” when using with `atom-ide-ui`

### ISSUE THREAD

**Issue by dtinth** [mybuddymichael/linter-elm-make#154]
Newly-released [atom-ide](http://blog.atom.io/2017/09/12/announcing-atom-ide.html) comes with the Diagnostics tab from Nuclide. However, the package tries to detect the presence of hardcoded package names:

https://github.com/mybuddymichael/linter-elm-make/blob/bee4a24a6c7c8247066e7bc415f2c31ee40022ae/lib/linter-elm-make.js#L28-L33

This causes this error message to appear:

![image](https://user-images.githubusercontent.com/193136/30388023-99975af6-98d8-11e7-9ac7-843e1ad8792d.png)

**Comment by halohalospecial** [comment]
Thanks @dtinth!
