### ISSUE TITLE
atom-ide-ui does not reflect error count in status bar

### ISSUE THREAD

**Issue by mrmurphy** [mybuddymichael/linter-elm-make#156]
<img width="334" alt="image" src="https://user-images.githubusercontent.com/1227109/30436801-527a5504-992a-11e7-9dfc-694a1f15a13e.png">

When I've got errors in my Elm file, the errors show up in the diagnostics panel, but the little error count in the bottom left corner always shows 0.

@halohalospecial I saw that you merged support yesterday. Was it supposed to just work with no changes?

**Comment by halohalospecial** [comment]
@splodingsocks, it should work with no changes :grin:  Do you have both `linter` and `diagnostics` (from `atom-ide-ui`) enabled?  I think you should only have 1 of those enabled.

![linter-atom-ide](https://user-images.githubusercontent.com/2138906/30468503-4c838c34-9a1e-11e7-95f7-926dcca65ed8.png)

**Comment by mrmurphy** [comment]
Huh! It's working now. I probably did have both of those enabled. Thank you!
