### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open 'C:/elmpractice\git\elmlang\elm-package.json'

### ISSUE THREAD

**Issue by bhaskarmac** [mybuddymichael/linter-elm-make#160]
1. I just wrote a simple hello world program and this linting error appeared
Note - There is no elm-package.json file in the directory

**Atom**: 1.20.1 ia32
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [linter-elm-make](https://github.com/mybuddymichael/linter-elm-make) package 0.25.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\elmpractice\git\elmlang\elm-package.json'

```
At fs.js:558

Error: ENOENT: no such file or directory, open 'C:\elmpractice\git\elmlang\elm-package.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at Object.readFileSync (~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/jsonfile/index.js:66:20)
    at /packages/linter-elm-make/lib/linter-elm-make.js:618:27)
    at emitTwo (events.js:106:13)
    at FSWatcher.emit (events.js:191:7)
    at /packages/linter-elm-make/node_modules/chokidar/index.js:196:15)
    at FSWatcher._emit (/packages/linter-elm-make/node_modules/chokidar/index.js:238:5)
    at FSWatcher.NodeFsHandler._handleFile (/packages/linter-elm-make/node_modules/chokidar/lib/nodefs-handler.js:275:10)
    at /packages/linter-elm-make/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
     -3:21.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -1:43.2.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -1:39.5.0 core:confirm (input.hidden-input)
     -1:33.2.0 intentions:highlight (input.hidden-input)
     -1:33.2.0 core:paste (input.hidden-input)
     -1:32.7.0 intentions:highlight (input.hidden-input)
     -1:32.5.0 core:save (input.hidden-input)
     -1:30.8.0 intentions:highlight (input.hidden-input)
     -1:30.7.0 core:close (input.hidden-input)
     -1:23.7.0 linter:lint (atom-text-editor.editor)
     -0:54.7.0 intentions:highlight (input.hidden-input)
     -0:54.5.0 core:close (input.hidden-input)
     -0:54.5.0 linter:lint (atom-text-editor.editor)
     -0:51.4.0 tree-view:remove (span.name.icon.database-icon.medium-yellow)
 15x -0:49.7.0 linter:lint (atom-text-editor.editor)
```

### Non-Core Packages

```
atom-easy-jsdoc 4.12.3 
atom-ide-ui 0.3.3 
busy-signal 1.4.3 
emmet 2.4.3 
es6-javascript 1.0.0 
file-icons 2.1.12 
ide-typescript 0.1.6 
intentions 1.1.5 
language-elm 1.5.0 
linter 2.2.0 
linter-elm-make 0.25.2 
linter-ui-default 1.6.10 
```

**Comment by halohalospecial** [comment]
Hi @bhaskarmac, did you add a `.js` file inside a `Native` directory?

**Comment by bhaskarmac** [comment]
Hi @halohalospecial,

I was starting with the Elm so I installed "linter, language-elm & linter-elm-make" package in Atom then I have just written hello world program in Elm in a directory and this directory dont have any "elm-package.json file" then continuouly the errors started popping in the Atom saying the "lint failed/timedout"  then there was option to create an issue, then I created an issue.

After installing the "linter-elm-make" do I need to perfom any steps, Am I missed anything? Could you please elaborate more about your comment above?

Please let me know if you need more information about this error or steps.

**Comment by halohalospecial** [comment]
@bhaskarmac, you can create an `elm-package.json` file by running `elm-package install` from the command line.  Though, `linter-elm-make` should notify you when it could not find `elm-package.json`.  Something like this should appear:

![no-elm-package-json](https://user-images.githubusercontent.com/2138906/30681981-67737b6a-9eda-11e7-8e63-d31fde05929f.png)

**Comment by bhaskarmac** [comment]
@halohalospecial, After `elm-package install` installing this issue, is resolved I think. This might be due to the elm-package.json file unavailability.

Don't know why its given initially "Uncaught Error"

Thanks for the help 👍
