### ISSUE TITLE
Settings/configuration button not found

### ISSUE THREAD

**Issue by johanhar** [mybuddymichael/linter-elm-make#161]
![packages](https://user-images.githubusercontent.com/661768/30804212-d451fddc-a1ec-11e7-845f-c93e45cd4f8c.png)

Other packages have got a button that navigates to "Settings", this package does not. Even tho the documentation states that we have to go there to insert the path to `elm-make`..

I am on macOS and is using Atom 1.20.1x64

**Comment by halohalospecial** [comment]
Hi @johanhar, can you try reinstalling the package? Thanks!

**Comment by johanhar** [comment]
I had to rebuild the packages. Still can't find the settings, but I located the `config.js` file and edited it manually.

**Comment by DavidLGoldberg** [comment]
I always forget how to fix this.  So for the next person:

Fuzzy find for "Incompatible packages" in command palette or click the little orange bug that appears in the lower right of the atom screen...

BTW, for me it did NOT list linter-elm-make ...but rather others... 

Upon restart it showed me linter-elm-make ....and after a rebuild of that everything works.
