### ISSUE TITLE
use of teletype broken when linter-elm-make is enabled

### ISSUE THREAD

**Issue by dbj** [mybuddymichael/linter-elm-make#181]
I'm running teletype 0.13.1, Atom 1.26.1, and linter-elm-make 0.28.3.  When I share a teletype session with another Atom user, and I bring up an Elm file for editing, the user's Atom editor freezes, though mine does not. If we edit other types of files, such as JS files, no problem, but as soon as we bring up an Elm file... freeze on the user's side.

This does not occur when I turn off linter-elm-make.  I have tried disabling and/or reinstalling teletype, linter-elm-make, and other related packages, and nothing seems to fix this issue.

Also note, the same thing happens with elmjutsu 8.1.0.

**Comment by dbj** [comment]
Just verified the same behavior with 0.13.2 of Teletype.

**Comment by halohalospecial** [comment]
@dbj, can you check the latest version (v0.28.5)?  Thanks!

**Comment by dbj** [comment]
No it is not fixed.  I am running Atom 1.27.1 and linter-elm 0.28.5.
