### ISSUE TITLE
Breaks with Elm 0.19.0

### ISSUE THREAD

**Issue by j-maas** [mybuddymichael/linter-elm-make#185]
When running with the default, outdated commands for make (`elm-make`) and packaging (`elm-package`), I get the following error:

```
I cannot find module 'Browser'.



Module 'Main' is trying to import it.



Potential problems could be:

  * Misspelled the module name

  * Need to add a source directory or new dependency to elm-package.json
```

I'm on Windows and I tried to set the commands to `elm make` (for building) and `elm` (for packaging), but then I get:

```
The command ""elm make"" is misspelled or could not be found.
```

If I try to set the build command to just `elm`, I get:

```
There is no C:\Users\Y0hy0h\Code\src\Main.elm command.



Run `elm` with no arguments to get more hints.
```

## Possible cause
I only have a slight suspicion, which is that this plugin uses an API that needs the command name to actually be a program. Therefore, it can't be composed of two words like `elm make` and crashes.

I'm not sure where to look for this and how to fix it. If there is a way I can help, please point me to it. :)

**Comment by halohalospecial** [comment]
Hi, linter-elm-make does not support Elm 0.19. You can try Elmjutsu v8.3.0 instead.

**Comment by halohalospecial** [comment]
Oh sorry, are you using Elm 0.18 or 0.19?

**Comment by j-maas** [comment]
@halohalospecial, Elmjutsu does not provide error highlighting as far as I can see. That is what I'd like to have linter-elm-make for.

This issue exists precisely because the plugin does not work with Elm 0.19.0. ;) But I'm unsure how to tackle it, so I can't open a PR.

**Comment by halohalospecial** [comment]
The just released version of Elmjutsu (v8.3.0) has error highlighting for Elm 0.19.

**Comment by j-maas** [comment]
@halohalospecial Thanks! I didn't find it mentioned anywhere, but once I deactivated linter-elm-make, it worked. I will be using Elmjutsu instead, thanks for the hint!

**Comment by halohalospecial** [comment]
Sorry, I forgot to add that to Elmjutsu's README.md haha.  There were lots of changes in Elm 0.19 that it was easier to add support in Elmjutsu than update linter-elm-make.
