### ISSUE TITLE
Types on hover

### ISSUE THREAD

**Issue by Fresheyeball** [mybuddymichael/linter-elm-make#23]
A la ide-haskell, type tooltips when hovering over a value would rock. Even better if they come with documentation for functions when available.

**Comment by Fresheyeball** [comment]
https://github.com/edubkendo/atom-elm/issues/22

**Comment by mrmurphy** [comment]
@Fresheyeball I'd love this, too. As shown in your screenshot, VS Code does this. Any idea how they do it? I know some compilers expose an api that'll return a type at a position in a file, but I don't think that Elm has that.

**Comment by mrmurphy** [comment]
Wow, just taking a glance, but it looks like they may have written their own JS code for extracting types from source:

https://github.com/sbrink/vscode-elm/blob/master/src/elmSymbol.ts

**Comment by mrmurphy** [comment]
Maybe we could pull in the VS Code plugin source as a dependency and make use of the things that make sense.

**Comment by Fresheyeball** [comment]
Are you sure vs-code does this? https://github.com/sbrink/vscode-elm/issues/25

**Comment by halohalospecial** [comment]
Will this suffice for the time being? (Only works on top-level values.)

https://atom.io/packages/elmjutsu

**Comment by Fresheyeball** [comment]
@halohalospecial you lovely person you. Obviously non-top level should be kept as a goal.

**Comment by mrmurphy** [comment]
I agree.

**Comment by halohalospecial** [comment]
I also agree!  It's a bit tedious to do at the moment, though.

I'll close the issue now because this feature  is out of scope of linter-elm-make :-)
