### ISSUE TITLE
Old errors not cleaned up.

### ISSUE THREAD

**Issue by Fresheyeball** [mybuddymichael/linter-elm-make#25]
So... There is a re-occurring problem in which the linter holds onto errors that are no longer valid. The only way I've found to fix the linter is to restart atom, which is not ideal. I'm not sure how to reproduce it or what could be causing it (race condition), but its very annoying.

**Comment by mybuddymichael** [comment]
I kind of wonder if this is somehow related to https://github.com/elm-lang/elm-make/issues/57.

**Comment by OvermindDL1** [comment]
I keep seeing this repeatedly as well.  `Ctrl+Alt+r` to reboot Atom fixes it, but is is annoying when I am staring at a line of code wondering wtf is wrong with it for a given error that I thought I fixed until I realize it is doing that again.  ^.^

**Comment by halohalospecial** [comment]
Hi, can you try the new release? The lint tasks are now queued to prevent race conditions.  Thanks! :-)

**Comment by OvermindDL1** [comment]
Will be testing while I work this week, if you hear nothing from me then it is good.  :-)

**Comment by halohalospecial** [comment]
Thanks! :+1:

**Comment by OvermindDL1** [comment]
So far it seems that I only have to Ctrl+Alt+R whenever I copy over my in-progress package into my elm-stuff directory directly (which is understandable that this would not catch).  Thus, so far so good.

**Comment by halohalospecial** [comment]
Ah yes, the assumption is that most operations are done inside Atom.  Why do you need to copy files to elm-stuff?

**Comment by OvermindDL1** [comment]
Just was working on an external package and running it in another app to test it out to verify no issues before publishing, not a common occurrence.

**Comment by halohalospecial** [comment]
@Fresheyeball, @OvermindDL1, is it safe to close this now? :)

**Comment by OvermindDL1** [comment]
Not remembering it lately so I would say good to close.
