### ISSUE TITLE
Quick Fix

### ISSUE THREAD

**Issue by halohalospecial** [mybuddymichael/linter-elm-make#27]
Hi!

I submitted a PR for the Quick Fix feature for review (https://github.com/mybuddymichael/linter-elm-make/pull/26).  It can somehow address issues https://github.com/mybuddymichael/linter-elm-make/issues/22 and https://github.com/mybuddymichael/linter-elm-make/issues/9.  Not sure if the feature is still within the scope of this package.  Should it be in a separate package instead?  Thanks!

**Comment by mybuddymichael** [comment]
Thanks for submitting this! I've commented on it over on the PR. Let's discuss it over there.
