### ISSUE TITLE
Report correct file paths

### ISSUE THREAD

**Issue by halohalospecial** [mybuddymichael/linter-elm-make#40]
Hi,

I found out that the "on-the-fly linting" release introduced bugs related to reporting the correct file path for an issue.  Clicking on a file path link in the bottom panel should open the associated file.

Mind reviewing PR https://github.com/mybuddymichael/linter-elm-make/pull/39 ?  Thanks!

**Comment by halohalospecial** [comment]
@mybuddymichael @splodingsocks I'll go ahead and publish this now since it looks like an important patch :)  Users might get confused with the incorrect squiggly lines.  I'll leave this issue open until you confirm it's working properly. Thanks!

**Comment by mrmurphy** [comment]
@halohalospecial please feel free to merge and deploy as you feel is necessary! Sorry, I've got a lot of side projects that I'm juggling. Thank you very much for the work you're doing here.

**Comment by halohalospecial** [comment]
It's all right.  Thanks!
