### ISSUE TITLE
linter-elm-make freeze when selecting an elm file

### ISSUE THREAD

**Issue by OvermindDL1** [mybuddymichael/linter-elm-make#58]
Everytime I open Atom and open an elm file the interface entirely freezes.

So after restarting it 20 times I opened the debugger and found the call stack of this every time I paused it, so it seems like a loop:

``` javascript
win32.dirname (path.js:320)
copySync (C:\Users\<username>\…opy-sync.js:22)
(anonymous function) (C:\Users\<username>\…opy-sync.js:40)
copySync (C:\Users\<username>\…opy-sync.js:37)
(anonymous function) (C:\Users\<username>\…opy-sync.js:40)
copySync (C:\Users\<username>\…opy-sync.js:37)
(anonymous function) (C:\Users\<username>\…opy-sync.js:40)
copySync (C:\Users\<username>\…opy-sync.js:37)
(anonymous function) (C:\Users\<username>\…opy-sync.js:40)
copySync (C:\Users\<username>\…opy-sync.js:37)
(anonymous function) (C:\Users\<username>\…opy-sync.js:40)
copySync (C:\Users\<username>\…opy-sync.js:37)
(anonymous function) (C:\Users\<username>\…opy-sync.js:40)
copySync (C:\Users\<username>\…opy-sync.js:37)
copyProjectToWorkDirectory (linter-elm-make.js:445)
lint (linter-elm-make.js:393)
promises.push.Promise.then._this.emitter.emit.linter (linter-registry.js:63)
(anonymous function) (linter-registry.js:62)
lint (linter-registry.js:60)
(anonymous function) (linter.coffee:98)
module.exports.Emitter.simpleDispatch (C:\Users\<username>\…t\lib\emit…:25)
module.exports.Emitter.emit (C:\Users\<username>\…\lib\emit…:125)
lint (editor-linter.js:175)
Commands.lint (commands.coffee:60)
Commands.subscriptions.add.atom.commands.add.linter:lint (commands.coffee:13)
module.exports.CommandRegistry.handleCommandEvent (C:\Users\<username>\…egistry.js:260)
(anonymous function) (C:\Users\<username>\…-registry.js:3)
module.exports.CommandRegistry.dispatch (C:\Users\<username>\…egistry.js:160)
forceLintActiveElmEditor (linter-elm-make.js:854)
(anonymous function) (linter-elm-make.js:169)
module.exports.Emitter.simpleDispatch (C:\Users\<username>\…t\lib\emit…:25)
module.exports.Emitter.emit (C:\Users\<username>\…\lib\emit…:125)
(anonymous function) (C:\Users\<username>\…ntainer.js:346)
module.exports.Emitter.simpleDispatch (C:\Users\<username>\…t\lib\emit…:25)
module.exports.Emitter.emit (C:\Users\<username>\…\lib\emit…:125)
module.exports.Pane.setActiveItem (C:\Users\<username>\…rc\pane.js:282)
module.exports.Pane.activateNextRecentlyUsedItem (C:\Users\<username>\…rc\pane.js:340)
commandRegistry.add.pane:show-next-recently-used-item (C:\Users\<username>\…commands.js:11)
module.exports.CommandRegistry.handleCommandEvent (C:\Users\<username>\…egistry.js:260)
(anonymous function) (C:\Users\<username>\…-registry.js:3)
module.exports.KeymapManager.dispatchCommandEvent (C:\Users\<username>\…ap\lib\ke…:580)
module.exports.KeymapManager.handleKeyboardEvent (C:\Users\<username>\…ap\lib\ke…:388)
module.exports.KeymapManager.terminatePendingState (C:\Users\<username>\…ap\lib\ke…:561)
module.exports.KeymapManager.handleKeyboardEvent (C:\Users\<username>\…ap\lib\ke…:432)
module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\<username>\…-handler.js:98)
(anonymous function) (C:\Users\<username>\…t-handler.js:3)
```

EDIT:  Ctrl+Enter apparently submits...  >.>

Either way, it seems to be iterating over every path in the project, including node_modules paths, which is sizable because of a certain svg pictograph package, and the program seems to be copying that entire thing out every single time a file is opened, and this takes about ten minutes (after waiting to see if it would complete now that I saw what was happening).  Why is it copying node_modules stuff and how do I get it to stop so it works in this project again (without removing this node_module as it is required for this project)?

**Comment by OvermindDL1** [comment]
Oh and yes, the "Work Directory" option is blank, which based on the text means it should not be copying anything, and yet...

**Comment by OvermindDL1** [comment]
Decided to see what all it was doing while copying files, thus:
- It seems to be copying everything to the System temporary directory
- The options passed in to copysync are:  `options = Object {preserveTimestamps: true, recursive: true, clobber: true, dereference: false}`
- `performCopy` seems to remain false for many (though not all) files, yet the iteration over the files takes a tremendous amount of time...

**Comment by halohalospecial** [comment]
Hi!

Thank you for the details.  If `Lint On The Fly` is enabled, the linter will copy the project files (`*.elm`, `elm-package.json`, and `elm-stuff`) into a temporary directory if `Work Directory` is not specified.  It will then just watch for changes after that.

**Comment by OvermindDL1** [comment]
The `copyProjectToWorkDirectory` function has this comment:

``` javascript
    // Recursively copy `.elm` files, `elm-package.json`, and `elm-stuff` from project directory to work directory.
    // Initial linting might take time depending on the project directory size.
```

A lot of time apparently, and from looking in the source for this function it does seem to only match out files that are in the project root `elm-stuff` directory, the `elm-package.json` file in the root project directory, or any files ending with `.elm`.

However, because of how it is implemented it will iterate over every-single-file testing each of those conditions.  Instead I would recommend parsing the elm-package.json file (it is just json after all) and look in the `"source-directories"` key for the directories to look in, at that point just copy out `"<projectroot>/elm-package.json"`, `"<projectroot>/elm-stuff/"`, and for each `"source-directory"` look in `"<projectroot>/<source_directory>"`.

However, why does `Lint On The Fly` require copying things out to a temporary directory anyway?  If it is just to check for changes then are file-stamps insufficient?

**Comment by halohalospecial** [comment]
Just copying those in "source-directories" might work :)

Files are copied to a temporary directory for this to be possible:

![lint-on-fly](https://github.com/mybuddymichael/linter-elm-make/blob/master/images/lint-on-fly.gif?raw=true)

In the screenshot, changes in a buffer affect the lints in another even if you haven't saved them yet.

What's your idea with the file-stamps?  Sorry, I'm a little slow right now.  I have flu and am getting sleepy.

**Comment by OvermindDL1** [comment]
Ah is it because you are having elm-make process all the files instead of stdin'ing them in?  That would probably work better with it.  Ignore the timestamps bit then.  :-)

I know how the flu is, was going around here not long ago.  >.>

But yes, source-directories + elm-package.json + elm-stuff would definitely be best, copying a gig of node_modules every load is... quite painful.  ^.^

**Comment by halohalospecial** [comment]
AFAIK, there's no stdin option in `elm-make` as it requires file path(s) as argument(s) and we couldn't just pass the changed files because of issues related to https://github.com/mybuddymichael/linter-elm-make/issues/32.

I was actually waiting for someone like you with a big enough project to test how `Lint On The Fly` will scale :)  The `Work Directory` is an optimization you can use so that files will not be copied anymore the next time you restart Atom.

I think the "source-directories" bit is a good idea :+1:

**Comment by OvermindDL1** [comment]
Lol, glad to be of service then.  NPM is always a bane of my existence.  ^.^

And yeah, this is a fairly huge project, Elm integration is rather new in it but growing rapidly (so much better than javascript).

**Comment by halohalospecial** [comment]
Haha thanks!

I'll rest for now (I'm in a different time zone).  I'll check your other messages tomorrow :)  Cheers!

**Comment by OvermindDL1** [comment]
Tested again with no working directory set, no freeze this time.  :-)

**Comment by halohalospecial** [comment]
Nice!

I hope the release did not break someone's workflow :D

![workflow](https://imgs.xkcd.com/comics/workflow.png)
