### ISSUE TITLE
Feature Request: If `brunch-config.js` exists, use the Elm project settings within it

### ISSUE THREAD

**Issue by OvermindDL1** [mybuddymichael/linter-elm-make#60]
If the `brunch-config.js` exists and is used for npm package management then it handles building elm in the project as well.  The file returns an object that you can get the information via `exports.config.plugins.elmBrunch`, and that is a dictionary with many useful arguments, but the important bits are the ones that define the project files, which as an example is:

``` javascript
    elmBrunch: {
      elmFolder: '.',
      mainModules: [
        'web/elm/MyApp1.elm',
        'web/elm/MyApp2.elm',
        'web/elm/MyApp3.elm',
        'web/elm/MyApp4.elm',
      ],
      // If specified, all mainModules will be compiled to a single file (optional and merged with outputFolder)
      outputFolder: 'web/static/js',
      outputFile: 'elm.js',
      makeParameters: ['--warn']
    }
```

The elmFolder defines the root path to the elm-package.json file (which should then be parsed for the `"source-directories"` entries to see the root path to the source files), as well as the mainModules (to be auto-setup for a project instead of needing to specify it manually inside atom) as well as possibly useful makeParameters.

**Comment by halohalospecial** [comment]
Not sure if this is still within the scope of this package as it's too specific?  Maybe just create another package that interacts with `linter-elm-make`?  Thoughts @splodingsocks, @mybuddymichael?

**Comment by mrmurphy** [comment]
Yeah, I'm not at all familiar with Brunch, but it seems like this would be a good candidate for a companion package to me.

**Comment by OvermindDL1** [comment]
Brunch is basically webpack but done right (and a lot older and a _lot_ faster).  Its configuration file is just a javascript file that returns an object in a global export dictionary, so it is very easy to parse (should just be an include if it exists, then access the dictionary).  But perhaps yeah.

**Comment by mybuddymichael** [comment]
I'd certainly argue for being very cautious about adding things like this into this plugin. It adds a lot of surface area that will likely go unused for 99% of users.

**Comment by OvermindDL1** [comment]
For note, this warning from the readme:

``` markdown
WARNING: Running elm-package install removes mainPaths from elm-package.json so you need to invoke Linter Elm Make: Set Main Paths again after.
```

Is definitely a bad feature.  As this information is already in brunch-config.js it would be nice if it could just use it from there, else put in, I'd say a new file, something like `.elm-linter` in the project or so?

**Comment by OvermindDL1** [comment]
Also, Phoenix uses brunch (as it is the fastest builder out, webpack is hell), and Elm is getting most popular in the phoenix community, so it is likely a significant portion of the userbase.  :-)

**Comment by halohalospecial** [comment]
Ah yes, putting it in another file like `.elm-linter` or `linter-elm-make.json` is the better option, esp. considering the recent changes to `linter-elm-make`.  The current way of doing it was just copied from the Sublime plugin :)  Will definitely implement this.  Thanks again for your suggestions!

**Comment by halohalospecial** [comment]
I'm getting more convinced by the usefulness of the brunch integration, but I feel it's a lot cleaner to put it in another package (especially if the webpack and gulp users out there also request for their own integrations).  Doing so will minimize the options (and surface area as @mybuddymichael said) for this package (side note: been contemplating lately if removing the `Work Directory` option is a good idea since it's adding complications :smile_cat:).

**Comment by halohalospecial** [comment]
Now saves `mainPaths` to `linter-elm-make.json` in the new release.  Thanks again @OvermindDL1!

**Comment by OvermindDL1** [comment]
Try out brunch sometime, it may be (a lot) older than gulp and webpack, but it fully uses the npm package system and is _significantly_ faster on compilation (I tried webpack a while back, over 8 minutes compilation time on my project, 20 second for brunch, it is a big project).  Although it is old it has been gaining fairly huge in popularity lately due to its speed and much easier configuration.  :-)

**Comment by halohalospecial** [comment]
I'm actually using elm-brunch with Phoenix :-)  I can help you create a companion package if you want.  Right now I'm just distracted creating another Elm-related package for Atom *wink wink*
