### ISSUE TITLE
Copy/pasting type annotations from warnings

### ISSUE THREAD

**Issue by rtfeldman** [mybuddymichael/linter-elm-make#63]
When an error or warning appears in the toggle box, I can select the text...

![screen shot 2016-07-21 at 11 34 46 am](https://cloud.githubusercontent.com/assets/1094080/17034360/35cf2666-4f37-11e6-899a-ef1f32f267a4.png)

...but it does not appear possible to copy it to the clipboard. This makes the `--warn` feature of "copy the generated annotation" much less useful!

**Comment by mybuddymichael** [comment]
Aw, bummer. Can I ask why you're copying the annotation? If it's to paste into your code, would [these "quick fix" commands](https://github.com/mybuddymichael/linter-elm-make#commands) help you?

**Comment by rtfeldman** [comment]
yuuuup! Totally did not know that was one of the quick fix options! 🎉 

I can leave this issue open, since it's still potentially worth fixing, but I'm unblocked, so feel free to close if you like. 😄

**Comment by halohalospecial** [comment]
What are you using to copy the text?  `Copy` is not in the context menu when you right-click, but `Cmd-C` / `Ctrl-C` works just fine :)  I believe this is a [linter](https://atom.io/packages/linter) issue, if ever.

**Comment by mybuddymichael** [comment]
@halohalospecial Are you on a Mac? I also cannot copy via <kbd>Cmd</kbd><kbd>C</kbd>.

**Comment by mybuddymichael** [comment]
I just pulled up a JS project and installed [linter-eslint](https://atom.io/packages/linter-eslint) and it suffers from the same problem. Maybe it's a general problem with [linter](https://github.com/steelbrain/linter)? Or maybe our themes are interfering with copying somehow?

**Comment by halohalospecial** [comment]
Can you try `Ctrl-C`?

See this: https://github.com/steelbrain/linter/issues/1083

@mybuddymichael I'm on Lubuntu right now.  Sorry, I just assumed it will also work with `Cmd-C` :D

**Comment by rafaelbiten** [comment]
Question on this. How can we add a shortcut for `quick fix`? First time using Atom and it isn't clear to me how to add a shortcut to this command. Tks!

edit: nvm! got it working with this:

```
'body':
  'ctrl-cmd-enter': 'linter-elm-make:quick-fix'
```

**Comment by halohalospecial** [comment]
Hi, it might not be obvious in the readme,  but it's below the `Linter Elm Make: Quick Fix All` section.

**Comment by rafaelbiten** [comment]
oh, sorry, I miss that section of the `readme` because I stopped at the `Quick Fix` section. The answer to my problem was right below it! Tks @halohalospecial !

**Comment by halohalospecial** [comment]
Might be better to move it to its own section.  Thanks for the feedback!
