### ISSUE TITLE
How to set installed package configuration?

### ISSUE THREAD

**Issue by canadaduane** [mybuddymichael/linter-elm-make#67]
The third step of the installation instructions reads:

```
Run which elm-make (Unix/Linux) or where.exe elm-make (Windows) from the command line and set the result as your executable path in this installed package's configuration.
```

Unfortunately, as a new Atom user, I don't know how to `set the result as your executable path in this installed package's configuration`. Any guidance?

**Comment by canadaduane** [comment]
Found it! For others:
- Press `Cmd-,` or `Ctrl-,`
- click `Packages`
- click the `linter-elm-make` package
- there is a Settings section, and under that a text input titled `The elm-make executable path.`
- replace `elm-make` with your path, e.g. `/usr/local/bin/elm-make`

**Comment by mybuddymichael** [comment]
This is good feedback though and thanks for taking the time to ask! I'll update our README to be more clear.

Thanks again!
