### ISSUE TITLE
/usr/bin/env: ‘node’: No such file or directoryat line 1 col 1

### ISSUE THREAD

**Issue by larfadin** [mybuddymichael/linter-elm-make#71]
Hi,

Everything was forking fine today. I juste update the package via npm and name everytime I save my file I have this issue:
`/usr/bin/env: ‘node’: No such file or directory at line 1 col 1`
My code is working great with elm reactor.
Node is also working I didn't change anything else just `apm upgrade`

**Comment by halohalospecial** [comment]
Hi!  Where did you see that message? Was it in the terminal, Atom console log, popup notification?  Can you also check if the elm-make executable path was configured properly in the package settings?  Thanks!

**Comment by larfadin** [comment]
Yes the elm make executable was configured properly. 
The message was in the bottom of the atom screen. Where it normally display error

**Comment by halohalospecial** [comment]
Can you run in dev mode (`atom -d`) and check the console messages with "[linter-elm-make]"?  Thanks!

**Comment by halohalospecial** [comment]
Oh sorry, do you mean the message is in the linter panel?  Try to delete your `elm-stuff`, then run `elm-package install -y` again :-)

**Comment by larfadin** [comment]
Yes the message is in the linter panel. I still got the issue after deleting elm-stuff in my project `~/dev/myProject/elm-stuff` and installing it again. I also try to uninstall linter elm make and reinstall again. But I got the same issue. Should I have an `elm-stuff` directory in my home ?

*EDIT: \*  When I run atom with `atom -d` linter works fine I got not node error.

**Comment by halohalospecial** [comment]
Hmm.  So it's working properly now if you run `atom -d`?

**Comment by halohalospecial** [comment]
What's your OS and Atom version?  Running `atom -d` vs `atom` should have no significant differences.  What were you using last time to run Atom?  Can you try running Atom using `atom` in the command line?

**Comment by larfadin** [comment]
Yes it works when starting atom with `atom -d`. But not with `atom`. There is not output in the console.
I'm using ubuntu 16.04 and atom 1.8.

When I start atom with command line it works. But not from the dash

**Comment by larfadin** [comment]
edit:
command `atom` : OK
command `atom -d` : OK
starting atom from icon: Linter does not work

**Comment by halohalospecial** [comment]
Ah yes, the console messages are just for debugging purposes (only outputs in dev mode) :-)  My guess is that Atom could not find your `elm-make` if launched from the dash.

**Comment by halohalospecial** [comment]
Can you try running `which elm-make` in the command line and copy the result and paste it onto the `The elm-make executable path` option in the `linter-elm-make` package settings?

**Comment by halohalospecial** [comment]
I tried opening Atom from the dash and I got `Error: spawn elm-make ENOENT`.  It worked again when I copied the result of `which elm-make` and pasted it onto package settings.  The previous settings was "elm-make" (default).
- I'm using Lubuntu 16.04 and Atom 1.8.

**Comment by larfadin** [comment]
Yes but I already done this. I did it again and the path is the same and I still got the issue.

**Comment by halohalospecial** [comment]
Hmm.  What did you mean by this: "I juste update the package via npm"?  What did you update via npm?  What's the command you used?

**Comment by larfadin** [comment]
apm\* sorry `apm install linter-elm-make`

**Comment by halohalospecial** [comment]
Is it possible that you have another `.atom` directory somewhere and that's what Atom is reading when ran from the dash?  Maybe the linter-elm-make settings (inside `config.cson`) in that directory is just the default.

**Comment by larfadin** [comment]
No I have only one atom install and it's from the webupd8 ppa

**Comment by halohalospecial** [comment]
Sorry, I'm running out of ideas right now :-)  Just to let you know, I installed Atom from https://atom.io using the "Download .deb" button.  Maybe you can try that.

**Comment by lyyourc** [comment]
I have the same issue, and it works via `atom -d` ~

```
OS X v10.11.4
Atom v1.9.8 (via brew cask)
elm v0.17.1

linter v1.11.16
linter-elm-make v0.15.1
```

**Comment by halohalospecial** [comment]
@DrakeLeung @larfadin I'm just guessing here, but this may be related to how `brew cask` or `webupd8 ppa` installed Atom.

Have you tried installing Atom from https://atom.io?

You can also check this: https://github.com/nodejs/node-v0.x-archive/issues/3911#issuecomment-8956154
or this: https://github.com/nodejs/node-v0.x-archive/issues/3911#issuecomment-18951288

**Comment by larfadin** [comment]
I just update those package via apm:

```
├── atom-beautify 0.29.9 -> 0.29.10
├── linter 1.11.14 -> 1.11.16
└── linter-elm-make 0.14.0 -> 0.16.0
```

And now it works ! I didn't change anything else.
You should try @drakeleung

**Comment by halohalospecial** [comment]
Glad that you have it working already! :+1:
