### ISSUE TITLE
Improve bottom panel

### ISSUE THREAD

**Issue by halohalospecial** [mybuddymichael/linter-elm-make#75]
Hi :-)

When I have `Show Inline Error Tooltips` enabled in the Linter package, the tooltip is blocking my code most of the time (especially when the error/warning message is long).

![ui1](https://cloud.githubusercontent.com/assets/2138906/17512458/7bf4551c-5e5a-11e6-85a1-1f5322a299ec.gif)

When I disable that option, I don't know anymore which message is related to the red/yellow squiggly at the cursor position.

My suggestion is to have something like this:

![ui2](https://cloud.githubusercontent.com/assets/2138906/17512480/98a118c6-5e5a-11e6-8d9d-504c3f678eb5.gif)

In the screenshot, the bottom panel is automatically scrolled to put the related message into view.  Also, the relevant message is highlighted.

What are your thoughts?  @mybuddymichael @splodingsocks @OvermindDL1

**Comment by mybuddymichael** [comment]
So are you saying that perhaps we should disable "Show Inline Error Tooltips" by default?

**Comment by halohalospecial** [comment]
No need to disable it by default since that option is shared by all linters.  Perhaps elm-make's long messages are uncommon among compilers.  Do you enable the inline tooltips?  What's your experience with those?  Maybe I'm the only one bothered by those haha.

**Comment by OvermindDL1** [comment]
Honestly I kind of like the inline, but it needs to be shorter, perhaps abbreviating it to a single line or two (with a note to look below in the bottom panel for details)?

**Comment by halohalospecial** [comment]
I'm happy with that, but I'm not sure if Linter supports that.  If possible, we'll just put the "overview" part of the message (from elm-make) in the tooltip.

**Comment by halohalospecial** [comment]
Oh, if the user wants to look at the message details, he/she still has to search the bottom panel for the one related to the cursor position...

**Comment by OvermindDL1** [comment]
> Oh, if the user wants to look at the message details, he/she still has to search the bottom panel for the one related to the cursor position...

The highlighting helps a ton to identify though.  :-)

I wonder if it would be better to make the highlighting more visible though, perhaps more irritating, so it stands out well, hmm...

**Comment by halohalospecial** [comment]
The inline tooltip and this feature can coexist.  It's up to the users if they want to disable the inline tooltips.  (We don't need to disable the tooltips by default.)

The highlighting is based on the theme and can be configured via css/less.

**Comment by halohalospecial** [comment]
@mybuddymichael what's your decision on this?  :-)  Should we add this feature or is the case not strong enough?

**Comment by mybuddymichael** [comment]
@halohalospecial I'm sorry, I'm just a little confused… What are exactly are you proposing that we do?

**Comment by halohalospecial** [comment]
Oh, sorry.  It's in the 2nd screenshot.  Moving the cursor position to a red/yellow squiggly will automatically scroll the bottom panel to highlight the message associated with that squiggly.  It doesn't matter if inline tooltips are enabled or disabled, since it will work either way.

**Comment by mybuddymichael** [comment]
Automatically scrolling the error pane makes a lot of sense to me.

I obviously love Elm's error messages, but, yes, sometimes they're just too much within the tooltip. I don't think I'd disable the tooltips because I appreciate them for Javascript and eslint. But if I could hover over an error then move down a line and still see the relevant message in the linter pane, that would be wonderful.

Really great idea, @halohalospecial. That said, there _may_ be some unforeseen consequence of us doing this that upsets some people, for some reason. How much work is this?

**Comment by halohalospecial** [comment]
Do you mean how big is the diff in terms of code?  What you see in the 2nd screenshot is already implemented here in my computer.  I'll push it to a different branch if you want.

I wanted to use [Linter UI](https://github.com/steelbrain/linter/wiki/Linter-UI-API), but it's not yet released according to the project lead of Linter.  So I just hacked the feature by adding <a> tags inside the message items in the bottom panel.  Moving the cursor to a squiggly scrolls the relevant anchor into view.  Only the messages for `linter-elm-make` will have this behavior, the other linter messages will not be affected.

Yep, my concern is the same as yours that other people might be upset by this since we'll be deviating from the normal Linter behavior.

Obligatory xkcd :-)
![workflow](https://imgs.xkcd.com/comics/workflow.png)

Side story:  Someone asked for help last night in Slack because he wanted to remove the inline tooltip that's blocking his Elm code :-)

If we're going to add this, it's best to make it toggleable (disabled by default).

**Comment by halohalospecial** [comment]
https://github.com/halohalospecial/linter-elm-make/commit/a739066ea4845acefd20ac9cce3919c89340b9bb

**Comment by mybuddymichael** [comment]
Sounds great.
