### ISSUE TITLE
Error Pane does not escape HTML reserved characters

### ISSUE THREAD

**Issue by diegonc** [mybuddymichael/linter-elm-make#76]
When an `elm-package.json` file has a `repository` field with an incorrect value, i.e. not hosted by GitHub, the `elm make` command will produce the following error message:

```
elm make
Error in $: Problem with the "repository" field.

The given domain does not start with <https://github.com/>
```

Under the same conditions the linter's error pane looks like this:

![image](https://cloud.githubusercontent.com/assets/261458/17645625/93c2a232-6181-11e6-8cc6-20e28bf15278.png)

It seems the angle brackets are not being escaped and are interpreted as some sort of tag because the text is truncated after `with`.

**Comment by halohalospecial** [comment]
@diegonc thanks for this!  I'll include the fix in the next release.
