### ISSUE TITLE
Silent failure when importing a specific module

### ISSUE THREAD

**Issue by thSoft** [mybuddymichael/linter-elm-make#8]
linter-elm-make works great, but stops working without any error message as soon as I import the module ElmFire from the package http://package.elm-lang.org/packages/ThomasWeiser/elmfire. If I remove the import, it works again.
To reproduce: clone https://github.com/ThomasWeiser/elmfire and start editing any Elm file.

**Comment by thSoft** [comment]
Linting also breaks when I import a module that (transitively) imports ElmFire.

**Comment by thSoft** [comment]
@ThomasWeiser, did you encounter this?

**Comment by ThomasWeiser** [comment]
As yet I have not much experience with the linter-elm-make or Atom in general. I got it working with the following sequence, so I don't think it's a specific problem with ElmFire.
1. `git clone https://github.com/ThomasWeiser/elmfire`
2. `cd elmfire/demo`
3. `make`
4. `atom .`
5. Open `src/Demo.elm`
6. Change something, then save

Sometimes it also helped to explicitly call the Lint command in Atom.

**Comment by thSoft** [comment]
The root cause of this is #11.
