### ISSUE TITLE
Please install the `linter` package in your Settings view.

### ISSUE THREAD

**Issue by OvermindDL1** [mybuddymichael/linter-elm-make#88]
The linter package is installed, although disabled, because currently testing a replacement linter package (same api, calls, everything), however 'linter-elm-make' is my only linter file out of over 20 that pops up this message.  Perhaps it is explicitly looking for it instead of something 'like' it?  Perhaps only test for its existence without requiring that it is active?

**Comment by halohalospecial** [comment]
Hi @OvermindDL1, I'm curious about the package you're trying out.  Is it already published?  If you're just testing it out, maybe clone the `linter-elm-make` source and remove the checks there?

Is it Linter v2.0?  The maintainer told me some days ago that we'll have goodies like inline tooltips with collapsible details and a UI for quick fixes similar to that of Intellij's Intentions (https://www.jetbrains.com/help/idea/2016.2/intention-actions.html)

**Comment by OvermindDL1** [comment]
I was testing out the facebook linter package, let me find it right quick since I am home, it is [Nuclide](https://atom.io/packages/nuclide), which has its own linter that replaces the functionality of the stock one but with 'more',  you keep the stock one installed but you have to disable it.  I'm still tweaking Nuclide at work but it seems to work decent'ish there, except with linter-elm-make.  I have it disabled currently as my lunch was over and wanted to get back into my old style at the time to get back to work, plus still unsure if I am keeping it or not.  :-)

I'd not heard of Linter v2, that would be quite nice indeed.  They should be mimicking what [KDevelop](https://www.kdevelop.org/) does, not IntelliJ.  KDevelop's popup has a simple mode (over a popup), an advanced mode (like the default picture on the above link, happens when you hit alt+space or whatever the combo one, I have mine set to always be enabled) with a few clickable things inside to do various things, jump to various areas, etc...  KDevelop is one of my favorate IDE's for any language (it itself only does C++ and Python by default, but it has a plugin interface that almost no one uses, v5 just came out recently, I need to update to it).

**Comment by cabaret** [comment]
I'm also running into this issue with Nuclide. I am using the nuclide-diagnostic package for my linter needs, and linter-elm-make keeps telling me I have not installed the linter package. I have it installed, but disabled.

**Comment by halohalospecial** [comment]
This should be fixed in v0.17.4.  Thanks!

**Comment by denisw** [comment]
This error has reappeared. This is because Nuclide has been merged to a single `nuclide` package, but this extension's code checks for the `nuclide-diagnostics-ui` package that doesn't exist anymore.

**Comment by halohalospecial** [comment]
Thanks @denisw!
