### ISSUE TITLE
Feature Request: Type Insert

### ISSUE THREAD

**Issue by Fresheyeball** [mybuddymichael/linter-elm-make#9]
```
Top-level value `foo` does not have a type annotation
The type annotation you want looks something like this:
       foo : Bar -> Baz
```

is a fairly common case this linter detects. Text in tooltips is not selectable, so developers still have to type out the annotation, even though its shown on screen. It would be nice to have the linter optionally insert the type annotation for you. Better yet if it can be done in batch for an entire module.

**Comment by mybuddymichael** [comment]
Let's talk about this on #26.
