### ISSUE TITLE
Error panel font size

### ISSUE THREAD

**Issue by simax** [mybuddymichael/linter-elm-make#97]
In `Atom,` is it possible to change the `font size` of the of the `error panel` that appears at the bottom of the screen?

**Comment by halohalospecial** [comment]
Hi @simax, you can edit your `~/.atom/styles.less`, where `~/.atom` is the Atom directory (I forgot the Windows equivalent :-)).  The changes should appear immediately.  You can also right click, then `Inspect Element` (like any other web page) to find out which DOM element is which.

Example:

```
linter-message {
  .linter-message-item {
  }
  .linter-highlight {
  }
  .linter-message-link {
  }
  linter-message-line {
    font-family: Ubuntu Mono;
    font-size: 16px;
  }
}
```

**Comment by simax** [comment]
Thanks @halohalospecial that worked perfectly.
